language: node_js
os: linux
dist: trusty
node_js:
  - '12'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: heroku
  api_key:
    secure: HEROKU_API_KEY
  on:
    branch: heroku
